### ISSUE TITLE
Conflit with Essentials.

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#2]
Hello !

The /kit is the same as Essentials, so there is a conflit ? :)

Could you add an aliase like : /akr kit or something like that ?

Thanks ! :)

**Comment by benjaminforras** [comment]
Hello!
This problem is already solved.

You can do the following:
Use: /akits, /akit or /kits

OR

Also you can disable the /kit command in Essentials:
If you don't find the "disabled-commands" property inside your Essentials's config.yml just add it to it. 
( https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L139 )

**Comment by TheIntelloBox** [comment]
Could you add a system to disable it in AdvancedKits because I use Essentials' kit too.

**Comment by benjaminforras** [comment]
You can use /essentials:kit.

**Comment by TheIntelloBox** [comment]
Yes but my players only know /kit of course. xD

**Comment by benjaminforras** [comment]
Currently there's no workaround. Sorry
